### PR TITLE
Bumped version of tools in singledigital/bay-circle image.

### PR DESCRIPTION
**Pull request by nicksantamaria**
The `singledigital/bay-circle:latest` image was last built 4 months ago, and some of the tools included are several years out of date.

Bumped the following tools to the latest releases:

- `docker`
- `docker-compose`
- `hub`

Given the long time between image builds there will be other software that gets bumped through apt.

### CODE REVIEW

**Comment by anthony-malkoun** [comment]
Where do we use this image?

**Comment by nicksantamaria** [comment]
Looks like 

- dtf-vic-gov-au 
- governor-vic-gov-au 

https://github.com/search?q=org%3Adpc-sdp+singledigital%2Fbay-circle%3Alatest&type=Code

**Comment by nicksantamaria** [comment]
Context of why I looked into this here - https://digital-engagement.atlassian.net/browse/DDIDO-263

**Comment by nicksantamaria** [comment]
I'm going to merge this, its super low risk

- the only builds this image is used for are already broken
- its just version bumps.

**Pull request merged**
