### PR TITLE
Switch from mailhog to mailpit.

### PR DESCRIPTION
**Pull request by nicksantamaria**
## Motivation

Mailhog appears to be abandonedware and has not had any patching done for several years. There is a successor project called mailpit which appears to have feature parity, and operates on the same ports as mailhog. Should be backward compatible for the purposes of SDP.

## Changes

- Updates to [mailpit](https://github.com/axllent/mailpit) which is actively supported.
- Also builds an image tagged "mailhog" for backward compatibility during the transition phase.

### CODE REVIEW

**Review by GROwen — APPROVED** [review]

**Comment by nicksantamaria** [comment]
@GROwen For a transition period I was hoping to tag this image with both `mailhog:6.x` and `mailpit:6.x` but could not figure out how to do that. Any thoughts?

**Comment by GROwen** [comment]
yep, duplicate the mailhog target in the bake file, rename it mailpit and add mailpit to the var IMAGES. I can take care of that in the morning.

**Comment by GROwen** [comment]
done
Screenshot 2024-07-05 at 4 35 29 PM

and done
Screenshot 2024-07-05 at 4 36 36 PM

I think this can be merged now @nicksantamaria

**Comment by nicksantamaria** [comment]
@GROwen one last change - lets rename the `mailhog` dir to `mailpit`.

**Comment by nicksantamaria** [comment]
https://github.com/dpc-sdp/ansible-role-sdp-tide-platform/pull/121

**Pull request merged**
