### PR TITLE
[SDPA-4350] Skip unprotected files error

### PR DESCRIPTION
**Pull request by vincent-gao**
### Jira
https://digital-engagement.atlassian.net/browse/SDPA-4350

### changes
1. turn off the protection warning.
image
2. we want this to be included into 1.30.1 release.

### CODE REVIEW

**Comment by nicksantamaria** [comment]
In addition to this, I think we should also add a `chmod 644` in sdp-ansible-upgrades.

**Comment by vincent-gao** [comment]
> In addition to this, I think we should also add a `chmod 644` in sdp-ansible-upgrades.

Thanks @nicksantamaria . 
https://github.com/dpc-sdp/sdp-ansible-upgrade/blob/master/roles/sdp-platform/templates/Dockerfile.cli.j2#L25
looks like we already have `644`

**Review by nicksantamaria — APPROVED** [review]

**Comment by vincent-gao** [comment]
The CI tests will pass after https://github.com/dpc-sdp/bay/pull/29 gets merged. So this PR can be merged.

**Comment by anthony-malkoun** [comment]
@nicksantamaria / @vincent-gao should this PR be against `2.x`? Does it get merged to `develop` or do we create our `3.x` branch now?

**Comment by vincent-gao** [comment]
> @nicksantamaria / @vincent-gao should this PR be against `2.x`? Does it get merged to `develop` or do we create our `3.x` branch now?

@anthony-malkoun I had a PR https://github.com/dpc-sdp/bay/pull/21 that merged to the develop branch, but seems like it doesn't  sync with 2.x or 3.x. yes, IMO it should be against `2.x`

**Comment by nicksantamaria** [comment]
There is already a `3.x` branch. For now lets continue merging PRs into `2.x` and I think we do periodic syncs of 2.x -> 3.x. Worth a call to discuss the details on how this works though.

**Comment by anthony-malkoun** [comment]
`2.x` is in production yeah? So merging this to `2.x` would create a new image that could go into production on next deploy before it's had any testing is how I understand it.

**Comment by vincent-gao** [comment]
> `2.x` is in production yeah? So merging this to `2.x` would create a new image that could go into production on next deploy before it's had any testing is how I understand it.

yeah, @anthony-malkoun ,  from my understanding, it should to be what you said above.  cc @nicksantamaria

**Comment by nicksantamaria** [comment]
Yes this is right, we're pivoting to a process with smaller incremental changes and less testing friction. Stuff going into the `2.x` branch will be deployed to develop/master throughout the normal development cycle.

Any major changes will go into 3.x so they can be tested in isolation.

**Pull request merged**
