### PR TITLE
Update to support `MARIADB_READREPLICA_HOSTS`

### PR DESCRIPTION
**Pull request by steveworley**
# Changes
- Updates read replica variable usage

### CODE REVIEW

**Comment by nicksantamaria** [comment]
@steveworley is this a breaking change? i.e. does it need to go out with the `5.x` branch?

**Comment by GROwen** [comment]
@steveworley Are there any Lagoon docs for this?

**Comment by nicksantamaria** [comment]
i read up on the read replicas docs for flexible server, and this isn't something thats going to offer us any advantages.

You have to provision read-replicas on a flexible server cluster, which is an extra instance, meaning extra cost. So you might as well increase the resource allocation on the main db cluster and gain benefits for writes too.

**Comment by nicksantamaria** [comment]
https://learn.microsoft.com/en-us/azure/mysql/flexible-server/concepts-read-replicas

**Pull request closed without merging**
