### PR TITLE
Added php-fpm_exporter binary and entrypoint script

### PR DESCRIPTION
**Pull request by nicksantamaria**
# Motivation

We would like to better understand our PHP applications performance characteristics.

# Changes

- Adds the [php-fpm_exporter](https://github.com/hipages/php-fpm_exporter) binary to the php-fpm
- Adds a entrypoint script to the php-fpm image which conditionally starts the php-fpm_metrics binary 
 
# Usage

- Set `PHP_FPM_EXPORTER_ENABLED=true`to run the metrics exporter
- Metrics data should be available at `container-ip:9253/metrics`

### CODE REVIEW

**Comment by nicksantamaria** [comment]
I've tested this out on the go-vic API app. Works well, no sidecars required.

**Review by steveworley — APPROVED** [review]

**Comment by steveworley** [comment]
Oooh that's awesome! It doesn't need a side car. That's pretty nifty.

**Pull request merged**
