### PR TITLE
[R20-1508] Added datapipeline env vars.

### PR DESCRIPTION
**Pull request by MdNadimHossain**
# Checklist
- [ ] Affected Issues have been mentioned in the Closing issues section
- [ ] Documentation has been written/updated.
- [ ] Changelog entry has been written

Explain the **details** for making this change. What existing problem does the pull request solve?

# Changelog Entry

# Closing issues
Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Review by krakerag — APPROVED** [review]
I saw the chat in slack about this and yes, this is just to allow global config for data pipelines natively in bay. All good

**Review by steveworley — APPROVED** [review]

**Comment by steveworley** [comment]
@MdNadimHossain is this change still needed? I believe Bay has moved to 6.x, if so we should change the base branch and resolve any conflicts that might come up from doing that.

**Comment by nicksantamaria** [comment]
Is this still relevant @MdNadimHossain ?

**Comment by MdNadimHossain** [comment]
@steveworley @nicksantamaria sorry missed the comments, yes still needed. All the projects are still using 5.x, Also we need this for budget in this release. So wondering is I should merge it to 5.x and do the same change for 6.x as well ?
cc: @GROwen

**Pull request merged**
